region: us-east-1

function_name: hometab
handler: hometab.handler
description: bolt lambda hometab app
runtime: python3.8
# role: lambda_basic_execution
role: role

# S3 upload requires appropriate role with s3:PutObject permission
# (ex. basic_s3_upload), a destination bucket, and the key prefix
# bucket_name: 'example-bucket'
# s3_key_prefix: 'path/to/file/'

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
# set aws lambda timeout to 15 minutes (900 seconds)
timeout: 60
# memory_size: 512
# concurrency: 500
#

# Experimental Environment variables
environment_variables:
    SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
    SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}


# If `tags` is uncommented then tags will be set at creation or update
# time.  During an update all other tags will be removed except the tags
# listed here.
#tags:
#    tag_1: foo
#    tag_2: bar